Adimin: []
pointparbreak: 350
TPtime: 200
invitetime: 1200
removetime: 1200
breaklist:
  - "STONE"
  - "GRANITE"
  - "DIORITE"
  - "ANDESITE"
  - "GRASS_BLOCK"
  - "DIRT"
  - "COBBLESTONE"
  - "OAK_LOG"
  - "SPRUCE_LOG"
  - "BIRCH_LOG"
  - "JUNGLE_LOG"
  - "ACACIA_LOG"
  - "DARK_OAK_LOG"
ideology:
  Agr: "農業主義"
  Agr2: "農業主義Lv2"
  Agr3: "農業主義Lv3"
  HAgr: "重農業主義"
  HAgr2: "重農業主義Lv2"
  HAgr3: "重農業主義Lv3"
  Prcm: "原始共産主義"
  Prcm2: "原始共産主義Lv2"
  Prcm3: "原始共産主義Lv3"
  Indy: "工業主義"
  Indy2: "工業主義Lv2"
  Indy3: "工業主義Lv3"
  Socy: "社会主義"
  Socy2: "社会主義Lv2"
  Socy3: "社会主義Lv3"
  comm: "共産主義"
  comm2: "共産主義Lv2"
  comm3: "共産主義Lv3"
  come: "商業主義"
  come2: "商業主義Lv2"
  come3: "商業主義Lv3"
  Hcom: "重商業主義"
  Hcom2: "重商業主義Lv2"
  Hcom3: "重商業主義Lv3"
  Cony: "企業主義"
  Cony2: "企業主義Lv2"
  Cony3: "企業主義Lv3"
  capi: "資本主義"
  capi2: "資本主義Lv2"
  capi3: "資本主義Lv3"
  Demo: "民主主義"
  Demo2: "民主主義Lv2"
  Demo3: "民主主義Lv3"
  mili: "軍事主義"
  mili2: "軍事主義Lv2"
  mili3: "軍事主義Lv3"
  mina: "軍国主義"
  mina2: "軍国主義Lv2"
  mina3: "軍国主義Lv3"
  reith: "帝国主義"
  reith2: "帝国主義Lv2"
  reith3: "帝国主義Lv3"
  fast: "ファシズム"
  fast2: "ファシズムLv2"
  fast3: "ファシズムLv3"
  reon: "宗教主義"
  reon2: "宗教主義Lv2"
  reon3: "宗教主義Lv3"
  god: "神権主義"
  god2: "神権主義Lv2"
  god3: "神権主義Lv3"
  prin: "原理主義"
  prin2: "原理主義Lv2"
  prin3: "原理主義Lv3"
  Neul: "中立主義"
  Neul2: "中立主義Lv2"
  Neul3: "中立主義Lv3"
  Noin: "非干渉主義"
  Noin2: "非干渉主義Lv2"
  Noin3: "非干渉主義Lv3"
  peace: "平和主義"
  peace2: "平和主義Lv2"
  peace3: "平和主義Lv3"