name: Second
version: 1.0.0
main: keizaiya.second.Potato
api-version: 1.14

commands:
  country:
    description: "国関連の処理に関するコマンド"
    usage: /<command>
  menu:
    description: "メニューを開くコマンドです"
    usage: /<command>
  chatmode:
    description: "チャットモードを変更します。"
    usage: /<command>
  admin:
    description: "管理者専用コマンド"
    usage: /<command>
    permission: inferno.admin
    permission-message: "これは管理者が使うコマンドです。よく見つけたね^^"
  Print:
    description: "通貨コマンド"
    usage: /<command>
  ToolColor:
    description: "カラー変えるコマンド"
    usage: /<command>
  playerinfo:
    description: "プレイヤーの情報をみれます"
    usage: /<command>
  selfkick:
    description: "自分をキックします"
    usage: /<command>
  w:
    description: "個人チャット用コマンドです"
    usage: /<command>
  dm:
    description: "個人チャット用コマンドです"
    usage: /<command>
  r:
    description: "個人チャット用コマンドです"
    usage: /<command>
  notice:
    description: "通知関連コマンド"
    usage: /<command>
  test:
    description: "テストコマンド(プラグイン開発用)"
    usage: /<command>
    permission: inferno.admin
    permission-message: "これは管理者が使うコマンドです。よく見つけたね^^"


permissions:
  inferno.admin:
    description: "adminコマンドの権限です"
    default: op